This is makeindex, version 2.15 [MiKTeX 2.9.6300 64-bit] (kpathsea + Thai support).
Scanning style file ./tesi.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file .\tesi.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file .\tesi.acr....done (8 lines written, 0 warnings).
Output written in .\tesi.acr.
Transcript written in .\tesi.alg.
